name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Set up Newman CLI
        run: npm install -g newman
      - name: Decode the .key file from GitHub Secrets
        run: echo "${{ secrets.CERTIFICATE_KEY }}" | base64 --decode > private.key
      - name: Decode the .cert file from GitHub Secrets
        run: echo "${{ secrets.CERTIFICATE_PEM }}" | base64 --decode > cert.pem
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          newman run Test-Postman.postman_collection.json -r cli,json --ssl-client-cert cert.pem --ssl-client-key private.key --timeout-request 60000 
      - name: Logout
        run: postman logout ${{ secrets.POSTMAN_API_KEY }}
